### PR TITLE
Support for Ruby 2.7+, extended test coverage and cache support for &blocks

### PR DESCRIPTION
**Pull request by oleander**
Various bug fixes and improvements. All of the below changes have test cases.

* `instance_variable_set` was replaced with `instance_eval` as `instance_variable_set` isn't implemented on `BasicObject`. 
* Support for Ruby 2.7+ by calling `ruby2_keywords` on  `new` and memoized methods.  This enables method delegation using `super` in versions above Ruby 2.7. Prior to 2.7, `new(*)` would treat `**kwargs` as part of  `*args`. I.e `new(1, a: 2)` would yield `super(1, {a: 2})`. In Ruby 2.7 `{a: 2}` would not be recognised as a keyword argument resulting in an `ArgumentError` error. The solution is to invoke `ruby2_keywords`.
* The argument `&block` is now part of the hash key.
* The hash key is now an array of arguments instead of a string. Methods on `Hash`, such as `Hash#key?` automatically call `#hash` on its input.
* Replaced the frozen, empty hash `MEMOIZED_HASH` used for cache storage with `Core::Constants::EMPTY_HASH`.
* The tests suite now tests for key overlap for three different types of input; `*args`, `**kwargs` and `&block` That is; two memoized method calls with different arguments should not return the same value. The arguments are generated using `Array#permutation` during testing. Removing any part of the hash key, say `id = [name, args, block]` to `id = [name, args]` causes the specs to fail as `call` and `call { }` yields the same cached value.
* `memoize` can now be called anywhere in the class. Before `klass.instance_method(name)` was called whenever `memoize` was invoked. As this is no longer part of the implementation, `memoize` can now be called before a method is defined. ~We might want to make sure the method we’re memoizing is defined at some point to prevent `super` from raising an error during runtime. Suggestions are welcome.~ Fixed in 16be5c0.
* Dynamically defined methods, i.e `method_missing` can now be memoized. 

I just read this in the contribution guidelines:

> A Pull Request will only be accepted if it addresses a specific issue that was reported previously, or fixes typos, mistakes in documentation etc.

Let me know if you want me to create issues for the above changes.

### CODE REVIEW

**Review by solnic — CHANGES_REQUESTED** [review]
Hey thanks for this PR, it looks like you've made great improvements but I can't accept it because it changes too many things at once. Would it be possible for you to break this down into separate PRs? Like, one that makes it compatible with MRI 3.0, then one that makes it work with BasicObjects, another one adding support for blocks etc.

**Comment by oleander** [comment]
Absolutely! I'll split them up into smaller chunks. Let's use this branch as a "dumping ground" until I'm finished with the split, then we can close it.

**Comment by oleander** [comment]
I'll wait with the remaining bullets until #47, #48, #49 has been closed.

**Comment by oleander** [comment]
I'll close this as the remaining features are no longer needed after merging #47, #48, and #49.

**Pull request closed without merging**
