### PR TITLE
Add Dry::Core::ClassAttributes

### PR DESCRIPTION
**Pull request by flash-gordon**
Formerly known as ClassMacros.
@solnic let me know if you want choose a better name for this :)

### CODE REVIEW

**Comment by flash-gordon** [comment]
e.g. could be ClassSettings or sutin

**Comment by timriley** [comment]
ClassMacros actually seems like a decent name to me – what was your thinking of changing it to "attributes"? Feels like using "attributes" might make it potentially confused with Ruby's attr_* class methods and their behaviour?

**Comment by flash-gordon** [comment]
@timriley well, the reasoning behind the name is simple, it acts pretty much like `class_attribute` from AS. Anyway, I don't like it tbh, but ClassMacro**s** is a bit misleading for me, I expect something more than one class-level method which defines reader/setter for you :) Or am I missing something?

**Comment by timriley** [comment]
Yeah, you're probably right :) It's a _little_ different to Ruby's typical "attributes" though, since they need assignment-style methods to have their values set.

Even with Rails' class attributes:

```ruby
class RailsThing
  class_attribute :foo

  self.foo = "hi"
end
```

Compared to this module, which has more of a "macro"-style behaviour (no assignment-style method):

```
class DryThing
  defines :foo

  foo "foo"
end
```

This is the why I was thinking a different name than "attributes" might be better.

**Comment by solnic** [comment]
I was against using the original name because "macros" sounds too serious :) It just defines get-or-set methods at the class level. No idea how to name it better though.

**Comment by timriley** [comment]
Fair enough :) I also wonder how much use case overlap this has with dry-configurable. Could we merge these somehow? Would we want to?

If we keep these as separate, supported things, I guess we'd also want to name this so its clearly different from dry-configurable (which is why "ClassSettings" may be problematic...)

**Comment by flash-gordon** [comment]
@timriley good point, what other options do we have? Options, properties, parameters?

**Comment by flash-gordon** [comment]
Also can be `Definitions/Define` since it provides the only method :)

**Comment by solnic** [comment]
Alternative idea: we add it to dry-configurable and call it a day /cc @AMHOL

**Comment by AMHOL** [comment]
@solnic you mean in the form of a `reader` option?

**Comment by solnic** [comment]
@AMHOL yes, we need class-level readers for config settings.

**Comment by AMHOL** [comment]
@solnic adding a kwarg to the [setting](https://github.com/dry-rb/dry-configurable/blob/master/lib/dry/configurable.rb#L83) method will re-introduce the [bug with hash default values](https://github.com/dry-rb/dry-configurable/issues/12), the options would be to make `default` a kwarg, or add a macro method to add readers for certain settings at the root level, i.e.

```ruby
class Config
  extend Dry::Configurable

  setting :root, default: './', processor: ->(v) { Pathname(v) }
  setting :etc
end
```

or

```ruby
class Config
  extend Dry::Configurable

  setting(:root, './') { |v| Pathname(v) }
  setting :etc
  setting_readers :root, :etc
end
```

**Pull request merged**
